ch_cookie_consent:
    categories:
        - 'analytics'
    use_logger: false         # logs user actions to database
    simplified: true          # when set to true the user can only deny or accept all cookies at once
    http_only: true           # sets HttpOnly on cookies
    csrf_protection: true     # the cookie consent form is csrf protected or not
#    form_action: $routeName # When set, xhr-Requests will only be sent to this route. Take care of having the route available.
    position: 'bottom'        # top, bottom
    theme: 'dark'             # light | dark option
