vich_uploader:
    db_driver: orm
    metadata:
        type: 'attribute'
    mappings:
        projects:
            uri_prefix: '/images/projects'
            upload_destination: '%kernel.project_dir%/public/images/projects'
            namer:
                service: 'Vich\UploaderBundle\Naming\PropertyNamer'
                options: { property: 'slug' }
        images:
            uri_prefix: '/images/projects'
            upload_destination: '%kernel.project_dir%/public/images/projects'
            namer:
                service: 'Vich\UploaderBundle\Naming\UniqidNamer'
        expenses:
            uri_prefix: '/uploads/expenses'
            upload_destination: '%kernel.project_dir%/var/uploads/expenses'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
