- name: restart messenger subsystem async workers
  shell: "supervisorctl start laureanoarquitectura-messenger-consume:*"
- name: restart scheduler subsystem async workers
  shell: "supervisorctl start laureanoarquitectura-scheduler-consume:*"
- name: fix full release directory apache ownership
  file:
    path: "{{ ansistrano_release_path.stdout }}"
    recurse: yes
    follow: yes
    owner: "{{ remote_system_user }}"
    group: "{{ remote_system_group }}"
- name: reload PHP FPM service
  service:
    state: reloaded
    name: "php{{ vhost_php_version }}-fpm"
- name: reload apache service
  service:
    state: reloaded
    name: "apache2"
